Rails3: model: user: use ::Query instead of Query
Test fails on Rails 3.0.

<pre>
Error:
test_destroy_should_update_wiki_contents(UserTest):
NoMethodError: undefined method `delete_all' for ActiveRecord::AttributeMethods::Query:Module
    app/models/user.rb:602:in `remove_references_before_destroy'
    test/unit/user_test.rb:298:in `test_destroy_should_update_wiki_contents'
</pre>

--HG--
extra : convert_revision : svn%3Ae93f8b46-1217-0410-a6f0-8f06a7374b81/trunk%408140