Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20111220-12
extra : transplant_source : kO%F2%A2%C4%10%E4B%CC%E0%A9%A2%D1%1Du%3E%9D%F1%B1%FA